### ISSUE TITLE
Add Microsoft Sculpt Mouse to the list

### ISSUE THREAD

**Issue by hmaarrfk** [paulrichards321/resetmsmice#2]
Thanks for making this.

I haven't had a chance to test it yet as I just unplugged my usb transceiver before finding this program, but these guys on the AUR forum say it works with the sculpt mouse.

https://bbs.archlinux.org/viewtopic.php?id=177916

Thanks for making this, you saved me $50. I was close to buying a logitech mouse to avoid this issue. 

Mark

**Comment by paulrichards321** [comment]
I have updated the README and pushed the changes! Thanks!
